import type { DemoCartItem, DemoProduct } from "./demo-types";

export const PRODUCT_IDS_BY_CATEGORY = {
  sofa: ["hinoki-low-sofa", "boucle-curve-sofa", "walnut-frame-sofa"],
  coffee_table: [
    "oak-frame-table",
    "travertine-plinth-table",
    "walnut-nesting-table",
  ],
  rug: ["woven-jute-rug", "wool-pebble-rug", "geometric-flatweave-rug"],
  floor_lamp: ["rice-paper-floor-lamp", "linen-dome-lamp", "brass-globe-lamp"],
  chair: ["ash-lounge-chair", "boucle-barrel-chair", "cognac-sling-chair"],
  plant: ["ceramic-olive-tree", "stone-planter-ficus", "teak-planter-palm"],
} as const;

export const DEMO_PRODUCTS: readonly DemoProduct[] = [
  {
    id: "hinoki-low-sofa",
    variantId: "demo-variant-hinoki-low-sofa",
    title: "Hinoki Low Sofa",
    category: "sofa",
    price: { amountMinor: 189900, currency: "USD" },
    dimensionsCm: { width: 210, height: 72, depth: 92 },
    styleTags: ["japandi", "light-wood", "low-profile"],
    color: "natural-cream",
    material: "hinoki-and-linen",
    description: "A low hinoki frame with calm linen cushions and soft edges.",
  },
  {
    id: "boucle-curve-sofa",
    variantId: "demo-variant-boucle-curve-sofa",
    title: "Boucle Curve Sofa",
    category: "sofa",
    price: { amountMinor: 229900, currency: "USD" },
    dimensionsCm: { width: 224, height: 78, depth: 98 },
    styleTags: ["modern-organic", "sculptural", "boucle"],
    color: "ivory",
    material: "boucle",
    description: "A softly curved sofa upholstered in tactile ivory boucle.",
  },
  {
    id: "walnut-frame-sofa",
    variantId: "demo-variant-walnut-frame-sofa",
    title: "Walnut Frame Sofa",
    category: "sofa",
    price: { amountMinor: 209900, currency: "USD" },
    dimensionsCm: { width: 205, height: 80, depth: 88 },
    styleTags: ["mid-century", "walnut", "tailored"],
    color: "oatmeal",
    material: "walnut-and-wool",
    description: "Tailored cushions sit within an exposed walnut frame.",
  },
  {
    id: "oak-frame-table",
    variantId: "demo-variant-oak-frame-table",
    title: "Oak Frame Table",
    category: "coffee_table",
    price: { amountMinor: 16900, currency: "USD" },
    dimensionsCm: { width: 105, height: 40, depth: 55 },
    styleTags: ["japandi", "light-oak"],
    color: "light-oak",
    material: "oak",
    description: "A low oak table with a softened architectural frame.",
  },
  {
    id: "travertine-plinth-table",
    variantId: "demo-variant-travertine-plinth-table",
    title: "Travertine Plinth Table",
    category: "coffee_table",
    price: { amountMinor: 24900, currency: "USD" },
    dimensionsCm: { width: 110, height: 38, depth: 60 },
    styleTags: ["modern-organic", "warm-minimal", "stone"],
    color: "ivory",
    material: "travertine",
    description: "A quiet stone-led alternative for the centre of the room.",
  },
  {
    id: "walnut-nesting-table",
    variantId: "demo-variant-walnut-nesting-table",
    title: "Walnut Nesting Table",
    category: "coffee_table",
    price: { amountMinor: 21900, currency: "USD" },
    dimensionsCm: { width: 95, height: 42, depth: 55 },
    styleTags: ["mid-century", "warm-walnut"],
    color: "walnut",
    material: "walnut",
    description: "Two compact surfaces in a rich, warm timber finish.",
  },
  {
    id: "woven-jute-rug",
    variantId: "demo-variant-woven-jute-rug",
    title: "Woven Jute Rug",
    category: "rug",
    price: { amountMinor: 34900, currency: "USD" },
    dimensionsCm: { width: 240, height: 1.2, depth: 170 },
    styleTags: ["japandi", "natural-fiber", "handwoven"],
    color: "natural-tan",
    material: "jute",
    description: "A warm handwoven jute rug with a simple bound edge.",
  },
  {
    id: "wool-pebble-rug",
    variantId: "demo-variant-wool-pebble-rug",
    title: "Wool Pebble Rug",
    category: "rug",
    price: { amountMinor: 52900, currency: "USD" },
    dimensionsCm: { width: 230, height: 2, depth: 180 },
    styleTags: ["modern-organic", "irregular", "plush"],
    color: "warm-ivory",
    material: "wool",
    description: "A plush wool rug shaped with a softly irregular pebble edge.",
  },
  {
    id: "geometric-flatweave-rug",
    variantId: "demo-variant-geometric-flatweave-rug",
    title: "Geometric Flatweave Rug",
    category: "rug",
    price: { amountMinor: 42900, currency: "USD" },
    dimensionsCm: { width: 240, height: 1, depth: 170 },
    styleTags: ["mid-century", "geometric", "flatweave"],
    color: "rust-multicolor",
    material: "wool-and-cotton",
    description: "Angular rust and mustard forms animate a slim flatweave rug.",
  },
  {
    id: "rice-paper-floor-lamp",
    variantId: "demo-variant-rice-paper-floor-lamp",
    title: "Rice Paper Floor Lamp",
    category: "floor_lamp",
    price: { amountMinor: 28900, currency: "USD" },
    dimensionsCm: { width: 36, height: 158, depth: 36 },
    styleTags: ["japandi", "paper", "soft-light"],
    color: "natural-white",
    material: "rice-paper-and-ash",
    description: "A tall paper lantern casts a gentle glow from an ash frame.",
  },
  {
    id: "linen-dome-lamp",
    variantId: "demo-variant-linen-dome-lamp",
    title: "Linen Dome Lamp",
    category: "floor_lamp",
    price: { amountMinor: 34900, currency: "USD" },
    dimensionsCm: { width: 58, height: 154, depth: 58 },
    styleTags: ["modern-organic", "linen", "sculptural"],
    color: "warm-ivory",
    material: "linen-and-plaster",
    description: "A broad linen dome balances a softly sculpted plaster stem.",
  },
  {
    id: "brass-globe-lamp",
    variantId: "demo-variant-brass-globe-lamp",
    title: "Brass Globe Lamp",
    category: "floor_lamp",
    price: { amountMinor: 31900, currency: "USD" },
    dimensionsCm: { width: 34, height: 162, depth: 34 },
    styleTags: ["mid-century", "brass", "opal-glass"],
    color: "aged-brass",
    material: "brass-and-glass",
    description: "An opal globe tops a precise aged-brass stem and base.",
  },
  {
    id: "ash-lounge-chair",
    variantId: "demo-variant-ash-lounge-chair",
    title: "Ash Lounge Chair",
    category: "chair",
    price: { amountMinor: 79900, currency: "USD" },
    dimensionsCm: { width: 74, height: 76, depth: 82 },
    styleTags: ["japandi", "ash", "woven"],
    color: "oatmeal",
    material: "ash-and-wool",
    description: "Sculpted ash arms frame a restrained woven lounge cushion.",
  },
  {
    id: "boucle-barrel-chair",
    variantId: "demo-variant-boucle-barrel-chair",
    title: "Boucle Barrel Chair",
    category: "chair",
    price: { amountMinor: 89900, currency: "USD" },
    dimensionsCm: { width: 82, height: 75, depth: 80 },
    styleTags: ["modern-organic", "boucle", "rounded"],
    color: "ivory",
    material: "boucle",
    description: "A compact barrel chair with a rounded, tactile boucle shell.",
  },
  {
    id: "cognac-sling-chair",
    variantId: "demo-variant-cognac-sling-chair",
    title: "Cognac Sling Chair",
    category: "chair",
    price: { amountMinor: 94900, currency: "USD" },
    dimensionsCm: { width: 72, height: 78, depth: 80 },
    styleTags: ["mid-century", "leather", "walnut"],
    color: "cognac",
    material: "leather-and-walnut",
    description: "Cognac leather is suspended across an angular walnut frame.",
  },
  {
    id: "ceramic-olive-tree",
    variantId: "demo-variant-ceramic-olive-tree",
    title: "Ceramic Olive Tree",
    category: "plant",
    price: { amountMinor: 18900, currency: "USD" },
    dimensionsCm: { width: 88, height: 170, depth: 82 },
    styleTags: ["japandi", "olive", "ceramic"],
    color: "silvery-green",
    material: "live-plant-and-ceramic",
    description: "A graceful olive tree planted in an off-white ceramic vessel.",
  },
  {
    id: "stone-planter-ficus",
    variantId: "demo-variant-stone-planter-ficus",
    title: "Stone Planter Ficus",
    category: "plant",
    price: { amountMinor: 22900, currency: "USD" },
    dimensionsCm: { width: 100, height: 180, depth: 90 },
    styleTags: ["modern-organic", "ficus", "stone"],
    color: "leaf-green",
    material: "live-plant-and-stone",
    description: "A lush ficus rises from a tactile pale stone planter.",
  },
  {
    id: "teak-planter-palm",
    variantId: "demo-variant-teak-planter-palm",
    title: "Teak Planter Palm",
    category: "plant",
    price: { amountMinor: 20900, currency: "USD" },
    dimensionsCm: { width: 110, height: 185, depth: 100 },
    styleTags: ["mid-century", "palm", "teak"],
    color: "leaf-green",
    material: "live-plant-and-teak",
    description: "Arching palm fronds stand in a raised slatted teak planter.",
  },
];

export const CART_ITEMS: readonly DemoCartItem[] = [
  { id: "coffee-table", name: "Coffee Table", priceMinor: 18900 },
  { id: "floor-lamp", name: "Floor Lamp", priceMinor: 12900 },
  { id: "rug", name: "Rug", priceMinor: 24900 },
  { id: "plant", name: "Plant", priceMinor: 5900 },
];
