import type { DemoCartItem, DemoProduct } from "./demo-types";

export const PRODUCT_IDS_BY_CATEGORY = {
  sofa: [
    "hinoki-low-sofa",
    "boucle-curve-sofa",
    "walnut-frame-sofa",
    "oat-linen-slipcover-sofa",
    "cane-back-teak-sofa",
  ],
  coffee_table: [
    "oak-frame-table",
    "travertine-plinth-table",
    "walnut-nesting-table",
    "ash-plinth-table",
    "teak-oval-table",
  ],
  rug: [
    "woven-jute-rug",
    "wool-pebble-rug",
    "geometric-flatweave-rug",
    "undyed-wool-shag-rug",
    "charcoal-border-rug",
  ],
  floor_lamp: [
    "rice-paper-floor-lamp",
    "linen-dome-lamp",
    "brass-globe-lamp",
    "oak-tripod-lamp",
    "ceramic-column-lamp",
  ],
  chair: [
    "ash-lounge-chair",
    "boucle-barrel-chair",
    "cognac-sling-chair",
    "oak-paper-cord-chair",
    "shearling-swivel-chair",
  ],
  plant: [
    "ceramic-olive-tree",
    "stone-planter-ficus",
    "teak-planter-palm",
    "stoneware-snake-plant",
    "rattan-basket-fern",
  ],
  side_table: [
    "oak-drum-side-table",
    "travertine-cube-side-table",
    "black-steel-tray-table",
    "walnut-pedestal-side-table",
    "rattan-nesting-side-table",
  ],
  bookshelf: [
    "oak-ladder-shelf",
    "walnut-low-shelf",
    "white-oak-cube-storage",
    "steel-and-ash-etagere",
    "hinoki-open-bookcase",
  ],
} as const;

export const DEMO_PRODUCTS: readonly DemoProduct[] = [
  {
    id: "hinoki-low-sofa",
    variantId: "demo-variant-hinoki-low-sofa",
    title: "Hinoki Low Sofa",
    category: "sofa",
    price: { amountMinor: 189900, currency: "USD" },
    dimensionsCm: { width: 210, height: 72, depth: 92 },
    styleTags: ["japandi", "light-wood", "low-profile"],
    color: "natural-cream",
    material: "hinoki-and-linen",
    description: "A low hinoki frame with calm linen cushions and soft edges.",
  },
  {
    id: "boucle-curve-sofa",
    variantId: "demo-variant-boucle-curve-sofa",
    title: "Boucle Curve Sofa",
    category: "sofa",
    price: { amountMinor: 229900, currency: "USD" },
    dimensionsCm: { width: 224, height: 78, depth: 98 },
    styleTags: ["modern-organic", "sculptural", "boucle"],
    color: "ivory",
    material: "boucle",
    description: "A softly curved sofa upholstered in tactile ivory boucle.",
  },
  {
    id: "walnut-frame-sofa",
    variantId: "demo-variant-walnut-frame-sofa",
    title: "Walnut Frame Sofa",
    category: "sofa",
    price: { amountMinor: 209900, currency: "USD" },
    dimensionsCm: { width: 205, height: 80, depth: 88 },
    styleTags: ["mid-century", "walnut", "tailored"],
    color: "oatmeal",
    material: "walnut-and-wool",
    description: "Tailored cushions sit within an exposed walnut frame.",
  },
  {
    id: "oat-linen-slipcover-sofa",
    variantId: "demo-variant-oat-linen-slipcover-sofa",
    title: "Oat Linen Slipcover Sofa",
    category: "sofa",
    price: { amountMinor: 174900, currency: "USD" },
    dimensionsCm: { width: 198, height: 76, depth: 94 },
    styleTags: ["modern-organic", "linen", "slipcovered"],
    color: "oat",
    material: "linen-and-poplar",
    description:
      "Washed linen slipcovers fall loosely over a deep, feather-topped seat.",
  },
  {
    id: "cane-back-teak-sofa",
    variantId: "demo-variant-cane-back-teak-sofa",
    title: "Cane Back Teak Sofa",
    category: "sofa",
    price: { amountMinor: 199900, currency: "USD" },
    dimensionsCm: { width: 192, height: 78, depth: 86 },
    styleTags: ["mid-century", "teak", "cane"],
    color: "clay",
    material: "teak-and-cane",
    description:
      "A woven cane back lightens a slim teak frame on tapered legs.",
  },
  {
    id: "oak-frame-table",
    variantId: "demo-variant-oak-frame-table",
    title: "Oak Frame Table",
    category: "coffee_table",
    price: { amountMinor: 16900, currency: "USD" },
    dimensionsCm: { width: 105, height: 40, depth: 55 },
    styleTags: ["japandi", "light-oak"],
    color: "light-oak",
    material: "oak",
    description: "A low oak table with a softened architectural frame.",
  },
  {
    id: "travertine-plinth-table",
    variantId: "demo-variant-travertine-plinth-table",
    title: "Travertine Plinth Table",
    category: "coffee_table",
    price: { amountMinor: 24900, currency: "USD" },
    dimensionsCm: { width: 110, height: 38, depth: 60 },
    styleTags: ["modern-organic", "warm-minimal", "stone"],
    color: "ivory",
    material: "travertine",
    description: "A quiet stone-led alternative for the centre of the room.",
  },
  {
    id: "walnut-nesting-table",
    variantId: "demo-variant-walnut-nesting-table",
    title: "Walnut Nesting Table",
    category: "coffee_table",
    price: { amountMinor: 21900, currency: "USD" },
    dimensionsCm: { width: 95, height: 42, depth: 55 },
    styleTags: ["mid-century", "warm-walnut"],
    color: "walnut",
    material: "walnut",
    description: "Two compact surfaces in a rich, warm timber finish.",
  },
  {
    id: "ash-plinth-table",
    variantId: "demo-variant-ash-plinth-table",
    title: "Ash Plinth Table",
    category: "coffee_table",
    price: { amountMinor: 18900, currency: "USD" },
    dimensionsCm: { width: 100, height: 36, depth: 58 },
    styleTags: ["japandi", "pale-ash", "plinth"],
    color: "pale-ash",
    material: "ash",
    description:
      "A pale ash slab rests on two chamfered plinths, low and quiet.",
  },
  {
    id: "teak-oval-table",
    variantId: "demo-variant-teak-oval-table",
    title: "Teak Oval Table",
    category: "coffee_table",
    price: { amountMinor: 23900, currency: "USD" },
    dimensionsCm: { width: 118, height: 38, depth: 64 },
    styleTags: ["mid-century", "teak", "oval"],
    color: "teak",
    material: "teak",
    description:
      "An oval teak top eases the walk around a tight seating group.",
  },
  {
    id: "woven-jute-rug",
    variantId: "demo-variant-woven-jute-rug",
    title: "Woven Jute Rug",
    category: "rug",
    price: { amountMinor: 34900, currency: "USD" },
    dimensionsCm: { width: 240, height: 1.2, depth: 170 },
    styleTags: ["japandi", "natural-fiber", "handwoven"],
    color: "natural-tan",
    material: "jute",
    description: "A warm handwoven jute rug with a simple bound edge.",
  },
  {
    id: "wool-pebble-rug",
    variantId: "demo-variant-wool-pebble-rug",
    title: "Wool Pebble Rug",
    category: "rug",
    price: { amountMinor: 52900, currency: "USD" },
    dimensionsCm: { width: 230, height: 2, depth: 180 },
    styleTags: ["modern-organic", "irregular", "plush"],
    color: "warm-ivory",
    material: "wool",
    description: "A plush wool rug shaped with a softly irregular pebble edge.",
  },
  {
    id: "geometric-flatweave-rug",
    variantId: "demo-variant-geometric-flatweave-rug",
    title: "Geometric Flatweave Rug",
    category: "rug",
    price: { amountMinor: 42900, currency: "USD" },
    dimensionsCm: { width: 240, height: 1, depth: 170 },
    styleTags: ["mid-century", "geometric", "flatweave"],
    color: "rust-multicolor",
    material: "wool-and-cotton",
    description: "Angular rust and mustard forms animate a slim flatweave rug.",
  },
  {
    id: "undyed-wool-shag-rug",
    variantId: "demo-variant-undyed-wool-shag-rug",
    title: "Undyed Wool Shag Rug",
    category: "rug",
    price: { amountMinor: 58900, currency: "USD" },
    dimensionsCm: { width: 250, height: 2.5, depth: 180 },
    styleTags: ["modern-organic", "undyed", "high-pile"],
    color: "chalk",
    material: "wool",
    description:
      "A deep undyed pile that softens footfall and warms a bare floor.",
  },
  {
    id: "charcoal-border-rug",
    variantId: "demo-variant-charcoal-border-rug",
    title: "Charcoal Border Rug",
    category: "rug",
    price: { amountMinor: 46900, currency: "USD" },
    dimensionsCm: { width: 240, height: 1.4, depth: 170 },
    styleTags: ["japandi", "hand-loomed", "bordered"],
    color: "soft-grey",
    material: "wool-and-linen",
    description:
      "A narrow charcoal border frames a hand-loomed field of soft grey.",
  },
  {
    id: "rice-paper-floor-lamp",
    variantId: "demo-variant-rice-paper-floor-lamp",
    title: "Rice Paper Floor Lamp",
    category: "floor_lamp",
    price: { amountMinor: 28900, currency: "USD" },
    dimensionsCm: { width: 36, height: 158, depth: 36 },
    styleTags: ["japandi", "paper", "soft-light"],
    color: "natural-white",
    material: "rice-paper-and-ash",
    description: "A tall paper lantern casts a gentle glow from an ash frame.",
  },
  {
    id: "linen-dome-lamp",
    variantId: "demo-variant-linen-dome-lamp",
    title: "Linen Dome Lamp",
    category: "floor_lamp",
    price: { amountMinor: 34900, currency: "USD" },
    dimensionsCm: { width: 58, height: 154, depth: 58 },
    styleTags: ["modern-organic", "linen", "sculptural"],
    color: "warm-ivory",
    material: "linen-and-plaster",
    description: "A broad linen dome balances a softly sculpted plaster stem.",
  },
  {
    id: "brass-globe-lamp",
    variantId: "demo-variant-brass-globe-lamp",
    title: "Brass Globe Lamp",
    category: "floor_lamp",
    price: { amountMinor: 31900, currency: "USD" },
    dimensionsCm: { width: 34, height: 162, depth: 34 },
    styleTags: ["mid-century", "brass", "opal-glass"],
    color: "aged-brass",
    material: "brass-and-glass",
    description: "An opal globe tops a precise aged-brass stem and base.",
  },
  {
    id: "oak-tripod-lamp",
    variantId: "demo-variant-oak-tripod-lamp",
    title: "Oak Tripod Lamp",
    category: "floor_lamp",
    price: { amountMinor: 26900, currency: "USD" },
    dimensionsCm: { width: 46, height: 150, depth: 46 },
    styleTags: ["japandi", "light-oak", "tripod"],
    color: "light-oak",
    material: "oak-and-linen",
    description:
      "Three splayed oak legs carry a narrow linen shade at reading height.",
  },
  {
    id: "ceramic-column-lamp",
    variantId: "demo-variant-ceramic-column-lamp",
    title: "Ceramic Column Lamp",
    category: "floor_lamp",
    price: { amountMinor: 32900, currency: "USD" },
    dimensionsCm: { width: 40, height: 158, depth: 40 },
    styleTags: ["modern-organic", "ceramic", "matte-glaze"],
    color: "chalk",
    material: "ceramic-and-cotton",
    description:
      "A hand-thrown ceramic column grounds a wide cotton drum shade.",
  },
  {
    id: "ash-lounge-chair",
    variantId: "demo-variant-ash-lounge-chair",
    title: "Ash Lounge Chair",
    category: "chair",
    price: { amountMinor: 79900, currency: "USD" },
    dimensionsCm: { width: 74, height: 76, depth: 82 },
    styleTags: ["japandi", "ash", "woven"],
    color: "oatmeal",
    material: "ash-and-wool",
    description: "Sculpted ash arms frame a restrained woven lounge cushion.",
  },
  {
    id: "boucle-barrel-chair",
    variantId: "demo-variant-boucle-barrel-chair",
    title: "Boucle Barrel Chair",
    category: "chair",
    price: { amountMinor: 89900, currency: "USD" },
    dimensionsCm: { width: 82, height: 75, depth: 80 },
    styleTags: ["modern-organic", "boucle", "rounded"],
    color: "ivory",
    material: "boucle",
    description: "A compact barrel chair with a rounded, tactile boucle shell.",
  },
  {
    id: "cognac-sling-chair",
    variantId: "demo-variant-cognac-sling-chair",
    title: "Cognac Sling Chair",
    category: "chair",
    price: { amountMinor: 94900, currency: "USD" },
    dimensionsCm: { width: 72, height: 78, depth: 80 },
    styleTags: ["mid-century", "leather", "walnut"],
    color: "cognac",
    material: "leather-and-walnut",
    description: "Cognac leather is suspended across an angular walnut frame.",
  },
  {
    id: "oak-paper-cord-chair",
    variantId: "demo-variant-oak-paper-cord-chair",
    title: "Oak Paper Cord Chair",
    category: "chair",
    price: { amountMinor: 64900, currency: "USD" },
    dimensionsCm: { width: 62, height: 74, depth: 60 },
    styleTags: ["japandi", "paper-cord", "oak"],
    color: "natural-cream",
    material: "oak-and-paper-cord",
    description:
      "Hand-wound paper cord seats a slender, almost weightless oak frame.",
  },
  {
    id: "shearling-swivel-chair",
    variantId: "demo-variant-shearling-swivel-chair",
    title: "Shearling Swivel Chair",
    category: "chair",
    price: { amountMinor: 99900, currency: "USD" },
    dimensionsCm: { width: 86, height: 78, depth: 84 },
    styleTags: ["modern-organic", "shearling", "swivel"],
    color: "bone",
    material: "shearling-and-steel",
    description:
      "A softly padded shearling shell turns on a low, brushed steel base.",
  },
  {
    id: "ceramic-olive-tree",
    variantId: "demo-variant-ceramic-olive-tree",
    title: "Ceramic Olive Tree",
    category: "plant",
    price: { amountMinor: 18900, currency: "USD" },
    dimensionsCm: { width: 88, height: 170, depth: 82 },
    styleTags: ["japandi", "olive", "ceramic"],
    color: "silvery-green",
    material: "live-plant-and-ceramic",
    description:
      "A graceful olive tree planted in an off-white ceramic vessel.",
  },
  {
    id: "stone-planter-ficus",
    variantId: "demo-variant-stone-planter-ficus",
    title: "Stone Planter Ficus",
    category: "plant",
    price: { amountMinor: 22900, currency: "USD" },
    dimensionsCm: { width: 100, height: 180, depth: 90 },
    styleTags: ["modern-organic", "ficus", "stone"],
    color: "leaf-green",
    material: "live-plant-and-stone",
    description: "A lush ficus rises from a tactile pale stone planter.",
  },
  {
    id: "teak-planter-palm",
    variantId: "demo-variant-teak-planter-palm",
    title: "Teak Planter Palm",
    category: "plant",
    price: { amountMinor: 20900, currency: "USD" },
    dimensionsCm: { width: 110, height: 185, depth: 100 },
    styleTags: ["mid-century", "palm", "teak"],
    color: "leaf-green",
    material: "live-plant-and-teak",
    description: "Arching palm fronds stand in a raised slatted teak planter.",
  },
  {
    id: "stoneware-snake-plant",
    variantId: "demo-variant-stoneware-snake-plant",
    title: "Stoneware Snake Plant",
    category: "plant",
    price: { amountMinor: 12900, currency: "USD" },
    dimensionsCm: { width: 46, height: 110, depth: 46 },
    styleTags: ["japandi", "sansevieria", "stoneware"],
    color: "deep-green",
    material: "live-plant-and-stoneware",
    description:
      "Upright sansevieria blades stand in a matte stoneware cylinder.",
  },
  {
    id: "rattan-basket-fern",
    variantId: "demo-variant-rattan-basket-fern",
    title: "Rattan Basket Fern",
    category: "plant",
    price: { amountMinor: 14900, currency: "USD" },
    dimensionsCm: { width: 70, height: 95, depth: 68 },
    styleTags: ["modern-organic", "fern", "rattan"],
    color: "leaf-green",
    material: "live-plant-and-rattan",
    description:
      "A full nest fern spills over the rim of a hand-woven rattan basket.",
  },
  {
    id: "oak-drum-side-table",
    variantId: "demo-variant-oak-drum-side-table",
    title: "Oak Drum Side Table",
    category: "side_table",
    price: { amountMinor: 27900, currency: "USD" },
    dimensionsCm: { width: 45, height: 55, depth: 45 },
    styleTags: ["japandi", "light-oak", "drum"],
    color: "light-oak",
    material: "oak",
    description:
      "A solid oak drum with a softened top edge, sized for a sofa arm.",
  },
  {
    id: "travertine-cube-side-table",
    variantId: "demo-variant-travertine-cube-side-table",
    title: "Travertine Cube Side Table",
    category: "side_table",
    price: { amountMinor: 39900, currency: "USD" },
    dimensionsCm: { width: 40, height: 45, depth: 40 },
    styleTags: ["modern-organic", "stone", "cube"],
    color: "ivory",
    material: "travertine",
    description:
      "A quarried travertine cube that serves as a table or an extra seat.",
  },
  {
    id: "black-steel-tray-table",
    variantId: "demo-variant-black-steel-tray-table",
    title: "Black Steel Tray Table",
    category: "side_table",
    price: { amountMinor: 21900, currency: "USD" },
    dimensionsCm: { width: 42, height: 56, depth: 42 },
    styleTags: ["mid-century", "blackened-steel", "tray"],
    color: "black",
    material: "steel",
    description:
      "A lift-off tray in a slim blackened frame, light enough to move often.",
  },
  {
    id: "walnut-pedestal-side-table",
    variantId: "demo-variant-walnut-pedestal-side-table",
    title: "Walnut Pedestal Side Table",
    category: "side_table",
    price: { amountMinor: 32900, currency: "USD" },
    dimensionsCm: { width: 38, height: 58, depth: 38 },
    styleTags: ["mid-century", "walnut", "pedestal"],
    color: "walnut",
    material: "walnut",
    description:
      "A turned walnut pedestal lifts a small round top to armrest height.",
  },
  {
    id: "rattan-nesting-side-table",
    variantId: "demo-variant-rattan-nesting-side-table",
    title: "Rattan Nesting Side Table",
    category: "side_table",
    price: { amountMinor: 24900, currency: "USD" },
    dimensionsCm: { width: 50, height: 52, depth: 50 },
    styleTags: ["japandi", "rattan", "nesting"],
    color: "natural-tan",
    material: "rattan-and-ash",
    description:
      "Two woven rattan tops nest together and pull apart when guests arrive.",
  },
  {
    id: "oak-ladder-shelf",
    variantId: "demo-variant-oak-ladder-shelf",
    title: "Oak Ladder Shelf",
    category: "bookshelf",
    price: { amountMinor: 44900, currency: "USD" },
    dimensionsCm: { width: 60, height: 180, depth: 36 },
    styleTags: ["japandi", "light-oak", "leaning"],
    color: "light-oak",
    material: "oak",
    description:
      "Five graduated oak shelves on a slim frame that leans to the wall.",
  },
  {
    id: "walnut-low-shelf",
    variantId: "demo-variant-walnut-low-shelf",
    title: "Walnut Low Shelf",
    category: "bookshelf",
    price: { amountMinor: 89900, currency: "USD" },
    dimensionsCm: { width: 120, height: 112, depth: 38 },
    styleTags: ["mid-century", "walnut", "credenza-height"],
    color: "walnut",
    material: "walnut",
    description:
      "A credenza-height walnut case for books, low enough to see across.",
  },
  {
    id: "white-oak-cube-storage",
    variantId: "demo-variant-white-oak-cube-storage",
    title: "White Oak Cube Storage",
    category: "bookshelf",
    price: { amountMinor: 69900, currency: "USD" },
    dimensionsCm: { width: 90, height: 150, depth: 36 },
    styleTags: ["modern-organic", "white-oak", "modular"],
    color: "pale-oak",
    material: "white-oak",
    description:
      "Nine open cubes in pale oak, sized for records and baskets.",
  },
  {
    id: "steel-and-ash-etagere",
    variantId: "demo-variant-steel-and-ash-etagere",
    title: "Steel and Ash Etagere",
    category: "bookshelf",
    price: { amountMinor: 79900, currency: "USD" },
    dimensionsCm: { width: 84, height: 190, depth: 34 },
    styleTags: ["mid-century", "blackened-steel", "etagere"],
    color: "black",
    material: "steel-and-ash",
    description:
      "Blackened steel uprights hold four floating ash shelves.",
  },
  {
    id: "hinoki-open-bookcase",
    variantId: "demo-variant-hinoki-open-bookcase",
    title: "Hinoki Open Bookcase",
    category: "bookshelf",
    price: { amountMinor: 94900, currency: "USD" },
    dimensionsCm: { width: 96, height: 176, depth: 32 },
    styleTags: ["japandi", "hinoki", "open-back"],
    color: "natural-cream",
    material: "hinoki",
    description:
      "An open-backed hinoki case that reads light against a plain wall.",
  },
];

export const CART_ITEMS: readonly DemoCartItem[] = [
  { id: "coffee-table", name: "Coffee Table", priceMinor: 18900 },
  { id: "floor-lamp", name: "Floor Lamp", priceMinor: 12900 },
  { id: "rug", name: "Rug", priceMinor: 24900 },
  { id: "plant", name: "Plant", priceMinor: 5900 },
];
